### ISSUE TITLE
Pull Request workflow

### ISSUE THREAD

**Issue by braxtonhall** [ubccpsc/310bot-2021W1#5]
Should have a workflow that runs checks like the tests and lint when someone makes a PR into main named `pull.yml`

```yml
name: tests

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
```

[This](https://github.com/marketplace/actions/poorlydefinedbehavioyr-nyc-reporter#example-usage) might be useful too.

- [x] Lint
- [x] Build
- [x] Tests (blocked on #3)
- [ ] Coverage reporting
